version: '3.7'

services:
  sftpgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sftpgo
    ports:
      - "2022:2022"
      - "8080:8080"
    environment:
      - SFTPGO_SFTPD__BINDINGS__0__PORT=2022
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8080
      - SFTPGO_LOG_LEVEL=info
      - SFTPGO_PLUGIN_AUTH=/sftpgo-plugin-auth
    volumes:
      - data:/var/lib/sftpgo
      - config:/etc/sftpgo

volumes:
  data:
  config:
